// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/comments" | "/admin/feed" | "/bookmarks" | "/communities" | "/drivers/[id]" | "/fantasy" | "/leaderboard" | "/live" | "/messages" | "/mod" | "/notifications" | "/p/[slug]" | "/post/[id]" | "/race/[season]/[round]" | "/settings" | "/stats" | "/teams/[id]" | "/user/[username]" | "/watch"
type AppRouteHandlerRoutes = "/api/achievements" | "/api/admin/comments" | "/api/admin/f1/sync" | "/api/admin/fantasy-images" | "/api/admin/feed-weights" | "/api/admin/posts" | "/api/admin/stats" | "/api/admin/users" | "/api/auth/code" | "/api/auth/delete" | "/api/auth/email" | "/api/auth/login" | "/api/auth/login/code" | "/api/auth/me" | "/api/auth/me/driver" | "/api/auth/me/flairs" | "/api/auth/password" | "/api/auth/preferences" | "/api/auth/register" | "/api/auth/reset-password" | "/api/auth/verify" | "/api/bookmarks" | "/api/comments/[id]/vote" | "/api/communities" | "/api/communities/[slug]" | "/api/communities/[slug]/moderators" | "/api/communities/[slug]/submissions" | "/api/communities/[slug]/submissions/[id]" | "/api/communities/[slug]/subscribe" | "/api/f1/calendar" | "/api/f1/live/current" | "/api/f1/live/stream" | "/api/f1/race/[season]/[round]" | "/api/f1/session/[sessionKey]" | "/api/f1/standings" | "/api/fantasy" | "/api/fantasy/leagues" | "/api/fantasy/leagues/join" | "/api/fantasy/team" | "/api/feed/seen" | "/api/feed/signal" | "/api/flairs" | "/api/follow" | "/api/followers" | "/api/following" | "/api/leaderboard" | "/api/live-chat" | "/api/messages" | "/api/messages/[peerId]" | "/api/moderate" | "/api/notifications" | "/api/onboarding" | "/api/posts" | "/api/posts/[id]" | "/api/posts/[id]/comments" | "/api/posts/[id]/pin" | "/api/posts/[id]/vote" | "/api/recommendations/communities" | "/api/recommendations/users" | "/api/reports" | "/api/standings" | "/api/stats/dashboard" | "/api/stats/driver/[id]" | "/api/stats/race/[year]/[round]/qualifying" | "/api/stats/race/[year]/[round]/results" | "/api/stats/team/[id]" | "/api/stats/timeline" | "/api/streams" | "/api/track" | "/api/upload" | "/api/user/[username]" | "/uploads/[...path]"
type PageRoutes = never
type LayoutRoutes = "/" | "/post/[id]" | "/user/[username]"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/comments": {}
  "/admin/feed": {}
  "/api/achievements": {}
  "/api/admin/comments": {}
  "/api/admin/f1/sync": {}
  "/api/admin/fantasy-images": {}
  "/api/admin/feed-weights": {}
  "/api/admin/posts": {}
  "/api/admin/stats": {}
  "/api/admin/users": {}
  "/api/auth/code": {}
  "/api/auth/delete": {}
  "/api/auth/email": {}
  "/api/auth/login": {}
  "/api/auth/login/code": {}
  "/api/auth/me": {}
  "/api/auth/me/driver": {}
  "/api/auth/me/flairs": {}
  "/api/auth/password": {}
  "/api/auth/preferences": {}
  "/api/auth/register": {}
  "/api/auth/reset-password": {}
  "/api/auth/verify": {}
  "/api/bookmarks": {}
  "/api/comments/[id]/vote": { "id": string; }
  "/api/communities": {}
  "/api/communities/[slug]": { "slug": string; }
  "/api/communities/[slug]/moderators": { "slug": string; }
  "/api/communities/[slug]/submissions": { "slug": string; }
  "/api/communities/[slug]/submissions/[id]": { "slug": string; "id": string; }
  "/api/communities/[slug]/subscribe": { "slug": string; }
  "/api/f1/calendar": {}
  "/api/f1/live/current": {}
  "/api/f1/live/stream": {}
  "/api/f1/race/[season]/[round]": { "season": string; "round": string; }
  "/api/f1/session/[sessionKey]": { "sessionKey": string; }
  "/api/f1/standings": {}
  "/api/fantasy": {}
  "/api/fantasy/leagues": {}
  "/api/fantasy/leagues/join": {}
  "/api/fantasy/team": {}
  "/api/feed/seen": {}
  "/api/feed/signal": {}
  "/api/flairs": {}
  "/api/follow": {}
  "/api/followers": {}
  "/api/following": {}
  "/api/leaderboard": {}
  "/api/live-chat": {}
  "/api/messages": {}
  "/api/messages/[peerId]": { "peerId": string; }
  "/api/moderate": {}
  "/api/notifications": {}
  "/api/onboarding": {}
  "/api/posts": {}
  "/api/posts/[id]": { "id": string; }
  "/api/posts/[id]/comments": { "id": string; }
  "/api/posts/[id]/pin": { "id": string; }
  "/api/posts/[id]/vote": { "id": string; }
  "/api/recommendations/communities": {}
  "/api/recommendations/users": {}
  "/api/reports": {}
  "/api/standings": {}
  "/api/stats/dashboard": {}
  "/api/stats/driver/[id]": { "id": string; }
  "/api/stats/race/[year]/[round]/qualifying": { "year": string; "round": string; }
  "/api/stats/race/[year]/[round]/results": { "year": string; "round": string; }
  "/api/stats/team/[id]": { "id": string; }
  "/api/stats/timeline": {}
  "/api/streams": {}
  "/api/track": {}
  "/api/upload": {}
  "/api/user/[username]": { "username": string; }
  "/bookmarks": {}
  "/communities": {}
  "/drivers/[id]": { "id": string; }
  "/fantasy": {}
  "/leaderboard": {}
  "/live": {}
  "/messages": {}
  "/mod": {}
  "/notifications": {}
  "/p/[slug]": { "slug": string; }
  "/post/[id]": { "id": string; }
  "/race/[season]/[round]": { "season": string; "round": string; }
  "/settings": {}
  "/stats": {}
  "/teams/[id]": { "id": string; }
  "/uploads/[...path]": { "path": string[]; }
  "/user/[username]": { "username": string; }
  "/watch": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/post/[id]": never
  "/user/[username]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
