export interface DriverOption {
  code: string
  name: string
  era: string
  team?: string
  /** True if on the current (2026) grid — used by the team/driver picker. */
  active?: boolean
}

const DRIVER_ID_MAP: Record<string, string> = {
  VER: "max_verstappen",
  NOR: "norris",
  PIA: "piastri",
  LEC: "leclerc",
  HAM: "hamilton",
  RUS: "russell",
  ANT: "antonelli",
  GAS: "gasly",
  HAD: "hadjar",
  ALB: "albon",
  SAI: "sainz",
  BEA: "bearman",
  TSU: "tsunoda",
  OCO: "ocon",
  STR: "stroll",
  DOO: "doohan",
  BOR: "bortoleto",
  COL: "colapinto",
  LIN: "arvid_lindblad",
  LAW: "lawson",
  HUL: "hulkenberg",
  MAG: "kevin_magnussen",
  ZHO: "zhou",
  BOT: "bottas",
  PER: "perez",
  RIC: "ricciardo",
  ALO: "alonso",
  VET: "vettel",
  RAI: "raikkonen",
  BUT: "button",
  ROS: "rosberg",
  MAS: "massa",
  WEB: "webber",
  KUB: "kubica",
  SCH: "michael_schumacher",
  HAK: "hakkinen",
  COU: "coulthard",
  BAR: "barrichello",
  MON: "montoya",
  TRU: "trulli",
  FIS: "fisichella",
  SEN: "senna",
  PRO: "prost",
  MAN: "mansell",
  PIQ: "piquet",
  BER: "berger",
  HIL: "damon_hill",
  VIL: "jacques_villeneuve",
  LAU: "lauda",
  JON: "jones",
  ROSBERG: "keke_rosberg",
  HUN: "hunt",
  FIT: "fittipaldi",
  AND: "andretti",
  SHE: "scheckter",
  STE: "stewart",
  CLA: "clark",
  BRAB: "brabham",
  HILLG: "graham_hill",
  SUR: "surtees",
  RIN: "rindt",
  FAN: "fangio",
  ASC: "ascari",
  FAR: "farina",
  HAW: "hawthorn",
  MOS: "stirling_moss",
}

export function getJolpicaDriverId(code: string): string {
  return DRIVER_ID_MAP[code.toUpperCase()] || code.toLowerCase().replace(/\s+/g, "_")
}

export const ALL_DRIVERS: DriverOption[] = [
  { code: "VER", name: "Max Verstappen", era: "2020s", team: "Red Bull", active: true },
  { code: "HAD", name: "Isack Hadjar", era: "2020s", team: "Red Bull", active: true },
  { code: "NOR", name: "Lando Norris", era: "2020s", team: "McLaren", active: true },
  { code: "PIA", name: "Oscar Piastri", era: "2020s", team: "McLaren", active: true },
  { code: "LEC", name: "Charles Leclerc", era: "2020s", team: "Ferrari", active: true },
  { code: "HAM", name: "Lewis Hamilton", era: "2020s", team: "Ferrari", active: true },
  { code: "RUS", name: "George Russell", era: "2020s", team: "Mercedes", active: true },
  { code: "ANT", name: "Andrea Kimi Antonelli", era: "2020s", team: "Mercedes", active: true },
  { code: "GAS", name: "Pierre Gasly", era: "2020s", team: "Alpine", active: true },
  { code: "COL", name: "Franco Colapinto", era: "2020s", team: "Alpine", active: true },
  { code: "ALB", name: "Alex Albon", era: "2020s", team: "Williams", active: true },
  { code: "SAI", name: "Carlos Sainz", era: "2020s", team: "Williams", active: true },
  { code: "BEA", name: "Oliver Bearman", era: "2020s", team: "Haas", active: true },
  { code: "OCO", name: "Esteban Ocon", era: "2020s", team: "Haas", active: true },
  { code: "LAW", name: "Liam Lawson", era: "2020s", team: "Racing Bulls", active: true },
  { code: "LIN", name: "Arvid Lindblad", era: "2020s", team: "Racing Bulls", active: true },
  { code: "BOR", name: "Gabriel Bortoleto", era: "2020s", team: "Audi", active: true },
  { code: "HUL", name: "Nico Hulkenberg", era: "2020s", team: "Audi", active: true },
  { code: "STR", name: "Lance Stroll", era: "2020s", team: "Aston Martin", active: true },
  { code: "ALO", name: "Fernando Alonso", era: "2020s", team: "Aston Martin", active: true },
  { code: "BOT", name: "Valtteri Bottas", era: "2020s", team: "Cadillac", active: true },
  { code: "PER", name: "Sergio Perez", era: "2020s", team: "Cadillac", active: true },
  { code: "TSU", name: "Yuki Tsunoda", era: "2020s" },
  { code: "DOO", name: "Jack Doohan", era: "2020s" },
  { code: "MAG", name: "Kevin Magnussen", era: "2020s" },
  { code: "ZHO", name: "Zhou Guanyu", era: "2020s" },
  { code: "RIC", name: "Daniel Ricciardo", era: "2020s" },
  { code: "VET", name: "Sebastian Vettel", era: "2010s" },
  { code: "RAI", name: "Kimi Raikkonen", era: "2010s" },
  { code: "BUT", name: "Jenson Button", era: "2010s" },
  { code: "ROS", name: "Nico Rosberg", era: "2010s" },
  { code: "MAS", name: "Felipe Massa", era: "2010s" },
  { code: "WEB", name: "Mark Webber", era: "2010s" },
  { code: "KUB", name: "Robert Kubica", era: "2010s" },
  { code: "SCH", name: "Michael Schumacher", era: "2000s" },
  { code: "HAK", name: "Mika Hakkinen", era: "2000s" },
  { code: "COU", name: "David Coulthard", era: "2000s" },
  { code: "BAR", name: "Rubens Barrichello", era: "2000s" },
  { code: "MON", name: "Juan Pablo Montoya", era: "2000s" },
  { code: "TRU", name: "Jarno Trulli", era: "2000s" },
  { code: "FIS", name: "Giancarlo Fisichella", era: "2000s" },
  { code: "SEN", name: "Ayrton Senna", era: "1990s" },
  { code: "PRO", name: "Alain Prost", era: "1990s" },
  { code: "MAN", name: "Nigel Mansell", era: "1990s" },
  { code: "PIQ", name: "Nelson Piquet", era: "1990s" },
  { code: "BER", name: "Gerhard Berger", era: "1990s" },
  { code: "HIL", name: "Damon Hill", era: "1990s" },
  { code: "VIL", name: "Jacques Villeneuve", era: "1990s" },
  { code: "LAU", name: "Niki Lauda", era: "1980s" },
  { code: "JON", name: "Alan Jones", era: "1980s" },
  { code: "ROSBERG", name: "Keke Rosberg", era: "1980s" },
  { code: "HUN", name: "James Hunt", era: "1970s" },
  { code: "FIT", name: "Emerson Fittipaldi", era: "1970s" },
  { code: "AND", name: "Mario Andretti", era: "1970s" },
  { code: "SHE", name: "Jody Scheckter", era: "1970s" },
  { code: "STE", name: "Jackie Stewart", era: "1970s" },
  { code: "CLA", name: "Jim Clark", era: "1960s" },
  { code: "BRAB", name: "Jack Brabham", era: "1960s" },
  { code: "HILLG", name: "Graham Hill", era: "1960s" },
  { code: "SUR", name: "John Surtees", era: "1960s" },
  { code: "RIN", name: "Jochen Rindt", era: "1960s" },
  { code: "FAN", name: "Juan Manuel Fangio", era: "1950s" },
  { code: "ASC", name: "Alberto Ascari", era: "1950s" },
  { code: "FAR", name: "Giuseppe Farina", era: "1950s" },
  { code: "HAW", name: "Mike Hawthorn", era: "1950s" },
  { code: "MOS", name: "Stirling Moss", era: "1950s" },
]
