var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/teams/[id]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1_0-7if._.js")
R.c("server/chunks/ssr/_1-vxwfk._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_1z7leb7.js")
R.c("server/chunks/ssr/node_modules_next_dist_0tej5c5._.js")
R.c("server/chunks/ssr/[root-of-the-server]__20mnb_1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_172hvm-._.js")
R.c("server/chunks/ssr/_10ewenj._.js")
R.c("server/chunks/ssr/src_app_error_tsx_15dgtgq._.js")
R.c("server/chunks/ssr/_01lsh4o._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0p8s4lh._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_teams_[id]_page_actions_0zq1sat.js")
R.m(542605)
module.exports=R.m(542605).exports
