var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/leaderboard/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0fhbvua._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0tej5c5._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_1z6jg8w.js")
R.c("server/chunks/ssr/[root-of-the-server]__20mnb_1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_172hvm-._.js")
R.c("server/chunks/ssr/_10ewenj._.js")
R.c("server/chunks/ssr/src_app_error_tsx_15dgtgq._.js")
R.c("server/chunks/ssr/_01lsh4o._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0p8s4lh._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_leaderboard_page_actions_10pjgoh.js")
R.m(593055)
module.exports=R.m(593055).exports
