// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/admin/comments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/comments">> = Specific
  const handler = {} as typeof import("../../src/app/admin/comments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/feed/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/feed">> = Specific
  const handler = {} as typeof import("../../src/app/admin/feed/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/bookmarks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bookmarks">> = Specific
  const handler = {} as typeof import("../../src/app/bookmarks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/communities/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/communities">> = Specific
  const handler = {} as typeof import("../../src/app/communities/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/drivers/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/drivers/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/drivers/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/fantasy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fantasy">> = Specific
  const handler = {} as typeof import("../../src/app/fantasy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/leaderboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leaderboard">> = Specific
  const handler = {} as typeof import("../../src/app/leaderboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/live/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/live">> = Specific
  const handler = {} as typeof import("../../src/app/live/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/messages">> = Specific
  const handler = {} as typeof import("../../src/app/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mod/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mod">> = Specific
  const handler = {} as typeof import("../../src/app/mod/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/p/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/p/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/p/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/post/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/post/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/post/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/race/[season]/[round]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/race/[season]/[round]">> = Specific
  const handler = {} as typeof import("../../src/app/race/[season]/[round]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/stats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stats">> = Specific
  const handler = {} as typeof import("../../src/app/stats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/stats/timing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stats/timing">> = Specific
  const handler = {} as typeof import("../../src/app/stats/timing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/teams/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teams/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/teams/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/user/[username]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/user/[username]">> = Specific
  const handler = {} as typeof import("../../src/app/user/[username]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/watch/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/watch">> = Specific
  const handler = {} as typeof import("../../src/app/watch/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/achievements/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/achievements">> = Specific
  const handler = {} as typeof import("../../src/app/api/achievements/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/comments">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/f1/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/f1/sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/f1/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/fantasy-images/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/fantasy-images">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/fantasy-images/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/feed-weights/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/feed-weights">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/feed-weights/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/posts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/posts">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/posts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/stats">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/code/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/code">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/code/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/delete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/delete">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/delete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/email">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/login/code/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login/code">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/login/code/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/me/driver/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me/driver">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/me/driver/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/me/flairs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me/flairs">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/me/flairs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/password">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/preferences/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/preferences">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/preferences/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/reset-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/reset-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/verify">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bookmarks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bookmarks">> = Specific
  const handler = {} as typeof import("../../src/app/api/bookmarks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/comments/[id]/vote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/comments/[id]/vote">> = Specific
  const handler = {} as typeof import("../../src/app/api/comments/[id]/vote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/communities/[slug]/moderators/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/communities/[slug]/moderators">> = Specific
  const handler = {} as typeof import("../../src/app/api/communities/[slug]/moderators/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/communities/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/communities/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/api/communities/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/communities/[slug]/submissions/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/communities/[slug]/submissions/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/communities/[slug]/submissions/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/communities/[slug]/submissions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/communities/[slug]/submissions">> = Specific
  const handler = {} as typeof import("../../src/app/api/communities/[slug]/submissions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/communities/[slug]/subscribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/communities/[slug]/subscribe">> = Specific
  const handler = {} as typeof import("../../src/app/api/communities/[slug]/subscribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/communities/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/communities">> = Specific
  const handler = {} as typeof import("../../src/app/api/communities/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/f1/calendar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/f1/calendar">> = Specific
  const handler = {} as typeof import("../../src/app/api/f1/calendar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/f1/live/current/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/f1/live/current">> = Specific
  const handler = {} as typeof import("../../src/app/api/f1/live/current/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/f1/live/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/f1/live/stream">> = Specific
  const handler = {} as typeof import("../../src/app/api/f1/live/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/f1/race/[season]/[round]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/f1/race/[season]/[round]">> = Specific
  const handler = {} as typeof import("../../src/app/api/f1/race/[season]/[round]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/f1/session/[sessionKey]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/f1/session/[sessionKey]">> = Specific
  const handler = {} as typeof import("../../src/app/api/f1/session/[sessionKey]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/f1/session/[sessionKey]/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/f1/session/[sessionKey]/stats">> = Specific
  const handler = {} as typeof import("../../src/app/api/f1/session/[sessionKey]/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/f1/sessions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/f1/sessions">> = Specific
  const handler = {} as typeof import("../../src/app/api/f1/sessions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/f1/standings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/f1/standings">> = Specific
  const handler = {} as typeof import("../../src/app/api/f1/standings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fantasy/leagues/join/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fantasy/leagues/join">> = Specific
  const handler = {} as typeof import("../../src/app/api/fantasy/leagues/join/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fantasy/leagues/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fantasy/leagues">> = Specific
  const handler = {} as typeof import("../../src/app/api/fantasy/leagues/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fantasy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fantasy">> = Specific
  const handler = {} as typeof import("../../src/app/api/fantasy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fantasy/team/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fantasy/team">> = Specific
  const handler = {} as typeof import("../../src/app/api/fantasy/team/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/feed/seen/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/feed/seen">> = Specific
  const handler = {} as typeof import("../../src/app/api/feed/seen/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/feed/signal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/feed/signal">> = Specific
  const handler = {} as typeof import("../../src/app/api/feed/signal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/flairs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/flairs">> = Specific
  const handler = {} as typeof import("../../src/app/api/flairs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/follow/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/follow">> = Specific
  const handler = {} as typeof import("../../src/app/api/follow/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/followers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/followers">> = Specific
  const handler = {} as typeof import("../../src/app/api/followers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/following/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/following">> = Specific
  const handler = {} as typeof import("../../src/app/api/following/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leaderboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leaderboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/leaderboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/live-chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/live-chat">> = Specific
  const handler = {} as typeof import("../../src/app/api/live-chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/messages/[peerId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messages/[peerId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/messages/[peerId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messages">> = Specific
  const handler = {} as typeof import("../../src/app/api/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/moderate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/moderate">> = Specific
  const handler = {} as typeof import("../../src/app/api/moderate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/onboarding/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/onboarding">> = Specific
  const handler = {} as typeof import("../../src/app/api/onboarding/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/posts/[id]/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/posts/[id]/comments">> = Specific
  const handler = {} as typeof import("../../src/app/api/posts/[id]/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/posts/[id]/pin/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/posts/[id]/pin">> = Specific
  const handler = {} as typeof import("../../src/app/api/posts/[id]/pin/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/posts/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/posts/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/posts/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/posts/[id]/vote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/posts/[id]/vote">> = Specific
  const handler = {} as typeof import("../../src/app/api/posts/[id]/vote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/posts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/posts">> = Specific
  const handler = {} as typeof import("../../src/app/api/posts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recommendations/communities/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recommendations/communities">> = Specific
  const handler = {} as typeof import("../../src/app/api/recommendations/communities/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recommendations/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recommendations/users">> = Specific
  const handler = {} as typeof import("../../src/app/api/recommendations/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports">> = Specific
  const handler = {} as typeof import("../../src/app/api/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/standings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/standings">> = Specific
  const handler = {} as typeof import("../../src/app/api/standings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stats/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stats/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/stats/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stats/driver/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stats/driver/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/stats/driver/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stats/race/[year]/[round]/qualifying/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stats/race/[year]/[round]/qualifying">> = Specific
  const handler = {} as typeof import("../../src/app/api/stats/race/[year]/[round]/qualifying/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stats/race/[year]/[round]/results/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stats/race/[year]/[round]/results">> = Specific
  const handler = {} as typeof import("../../src/app/api/stats/race/[year]/[round]/results/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stats/team/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stats/team/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/stats/team/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stats/timeline/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stats/timeline">> = Specific
  const handler = {} as typeof import("../../src/app/api/stats/timeline/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/streams/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/streams">> = Specific
  const handler = {} as typeof import("../../src/app/api/streams/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/track/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/track">> = Specific
  const handler = {} as typeof import("../../src/app/api/track/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/user/[username]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/[username]">> = Specific
  const handler = {} as typeof import("../../src/app/api/user/[username]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/uploads/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/uploads/[...path]">> = Specific
  const handler = {} as typeof import("../../src/app/uploads/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/post/[id]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/post/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/post/[id]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/user/[username]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/user/[username]">> = Specific
  const handler = {} as typeof import("../../src/app/user/[username]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
